parameters:
    database_host: localhost
    database_port: '3306'
    database_name: 'test'
    database_user: 'travis'
    database_password: 'travis'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~
    secret: ThisTokenIsNotSoSecretChangeIt
