language: php

php:
  - 7.1

addons:
  mariadb: '10.3'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-add travis/php/php.ini
  - cp travis/app/config/parameters.yml app/config/parameters.yml
  - composer self-update

install: composer install -o

before_script:
  - mysql -e "CREATE DATABASE test;"
  - mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis';"
  - mysql -e "grant all on test.* to 'travis'@'localhost';"

script:
  - bin/phpcs --ignore=/vendor/*,/app/*,/web/*,/bin/* --extensions=php --encoding=utf-8 --standard=PSR12 -np .
  - php app/console doctrine:schema:create --env=test
  - php app/console doctrine:schema:validate --env=test
